name: Workflow Event
on: 
  workflow_run:
    workflow: Pull Request Target
    types: [completed,failed]
jobs:
  workflow_event_job:
    runs-on: ubuntu-latest
    steps:
      - name: display running after pull target action
        run: |
          echo "running after the putll target action"
      - name: displaying current branch refrence and commit code...
        run: |
          echo "current refrence is $GITHUB_REF"
          echo "current sha is $GITHUB_SHA"
