name: Joke Composite Action
description: This action tells a joke using a composite action.
inputs:
  funny_joke:
    description: A keyword to get a funny joke.
    required: true
    default: "false"
  upload_joke:
    description: A flag to upload the joke to a server.
    required: false
    default: "false"
outputs:
  joke_output:
    description: The joke that was told.
    value: ${{steps.tell_joke.outputs.joke}}
runs:
  using: "composite"
  steps: 
    - name: Tell a joke
      shell: bash
      id: tell_joke
      run: |
        eof="123456789"
        echo "joke<<$eof" >> $GITHUB_OUTPUT
        curl -s https://icanhazdadjoke.com/ >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        echo "$eof" >> $GITHUB_OUTPUT
    - name: write to file
      shell: bash
      run: |
        echo "${{steps.tell_joke.outputs.joke}}" > joke.txt
        
    - name: Upload joke
      if: ${{inputs.upload_joke == 'true'}}
      uses: actions/upload-artifact@v4
      with:
        name: joke-artifact
        path: joke.txt

    - name: testing turnury operator
      shell: bash
      id: turnury_tes
      env:
        Hello: ${{ inputs.funny_joke == 'true' && 'funny' || 'not_funny' }}
      run: |
        echo "Joke type: ${{env.Hello}}"

    